import { useEffect, useMemo, useRef, useState } from "react";
import { createRoot } from "react-dom/client";
import { ArrowRight, Minus, Plus, ShoppingCart, ScanLine, MapPin, Trash2 } from "lucide-react";
import "./style.css";

// Vercel 환경변수에 Cloud Run 주소를 넣으면 웹 배포에서도 같은 코드로 동작한다.
// 로컬 개발에서는 기존 Python 서버 주소를 기본값으로 사용한다.
const API = import.meta.env.VITE_API_BASE_URL || "http://127.0.0.1:8000/api";
const seed = [
  [1, "깐마늘", "채소", 6980, "500 g", "A-11"], [2, "부사 사과", "과일", 11980, "4입", "A-21"],
  [3, "대파", "채소", 2980, "1단", "A-12"], [4, "돼지고기 앞다리살", "정육", 15800, "800 g", "B-21"],
  [5, "양파", "채소", 3980, "1 kg", "A-13"], [6, "슬라이스 햄", "냉장", 7280, "400 g", "B-22"],
  [7, "당근", "채소", 3480, "1 kg", "A-14"], [8, "동물복지 계란", "냉장", 8980, "20구", "B-23"],
  [9, "흰다리 새우", "수산", 12980, "400 g", "B-31"], [10, "우유 식빵", "베이커리", 4280, "450 g", "C-11"]
].map(([id, name, category, price, unit, zone]) => ({ id, name, category, price, unit, zone, storage_type: "신선식품" }));
const money = new Intl.NumberFormat("ko-KR", { style: "currency", currency: "KRW", maximumFractionDigits: 0 });
const productAliases = {
  "깐마늘": ["깐마늘", "마늘", "garlic", "galic", "peeledgarlic"],
  "부사 사과": ["부사사과", "사과", "apple", "fujiapple"],
  "대파": ["대파", "파", "greenonion", "scallion", "springonion", "l_onion"],
  "돼지고기 앞다리살": ["돼지고기앞다리살", "돼지고기", "고기", "pork", "raw_pork", "porkshoulder", "meat"],
  "양파": ["양파", "onion"], "슬라이스 햄": ["슬라이스햄", "햄", "ham", "slicedham", "sliceham"],
  "당근": ["당근", "carrot"], "동물복지 계란": ["동물복지계란", "계란", "egg", "eggs"],
  "흰다리 새우": ["흰다리새우", "새우", "shrimp", "prawn"], "우유 식빵": ["우유식빵", "식빵", "bread", "milkbread", "toast"]
};
// Roboflow classes may include a number or punctuation (for example "대파-1", "green_onion (2)").
const normalizeLabel = value => String(value || "").toLowerCase()
  .replace(/[^a-z0-9가-힣]/g, "").replace(/\d+$/, "");
const CONFIRMATION_FRAMES = 2;
const MIN_CONFIDENCE_PERCENT = 75;
const resolveProductName = (label, products) => {
  const normalized = normalizeLabel(label);
  if (!normalized) return null;
  const aliasEntry = Object.entries(productAliases).find(([, aliases]) => aliases.some(alias => normalized === normalizeLabel(alias)));
  return products.find(product => normalizeLabel(product.name) === normalized
    || aliasEntry?.[1].includes(normalizeLabel(product.name)))?.name || null;
};

function useCameraStream() { const [stream, setStream] = useState(null); const [cameraError, setCameraError] = useState(""); useEffect(() => { let active = true; let current; navigator.mediaDevices?.getUserMedia({ video: { facingMode: "user", width: { ideal: 1280 }, height: { ideal: 720 } }, audio: false }).then(value => { current = value; if (active) setStream(value); else value.getTracks().forEach(track => track.stop()); }).catch(error => { if (active) setCameraError(error.name === "NotAllowedError" ? "카메라 권한을 허용해 주세요." : "카메라를 찾을 수 없습니다."); }); return () => { active = false; current?.getTracks().forEach(track => track.stop()); }; }, []); return { stream, cameraError }; }
function attachStream(element, stream) { if (element && stream && element.srcObject !== stream) { element.srcObject = stream; element.play().catch(() => {}); } }

function App() {
  const [products, setProducts] = useState(seed); const [recommendations, setRecommendations] = useState([]); const [cart, setCart] = useState(() => { try { return JSON.parse(localStorage.getItem("smart-cart-items")) || {}; } catch { return {}; } }); const [bagSelected, setBagSelected] = useState(() => localStorage.getItem("smart-cart-bag") === "true"); const [paymentComplete, setPaymentComplete] = useState(false); const [view, setView] = useState("main"); const [selectedRecipe, setSelectedRecipe] = useState(null); const [scanState, setScanState] = useState("ready"); const [lastRecognition, setLastRecognition] = useState(null); const [recognitionToast, setRecognitionToast] = useState(null); const [debugInfo, setDebugInfo] = useState({ status: "카메라 프레임 대기 중", raw: "-", mapped: "-", count: 0, error: "" }); const [showDebug, setShowDebug] = useState(false); const [pendingExit, setPendingExit] = useState(null); const lastRegisteredRef = useRef(""); const candidateRef = useRef({ name: null, count: 0 }); const toastTimerRef = useRef(null); const scanInFlightRef = useRef(false); const mainVideoRef = useRef(null); const scanRef = useRef(null); const { stream, cameraError } = useCameraStream();
  useEffect(() => { fetch(`${API}/products`).then(r => r.ok ? r.json() : Promise.reject()).then(list => { setProducts(list); setCart(current => Object.entries(current).reduce((next, [name, qty]) => { const dbName = resolveProductName(name, list) || name; next[dbName] = (next[dbName] || 0) + qty; return next; }, {})); }).catch(() => {}); }, []);
  useEffect(() => { localStorage.setItem("smart-cart-items", JSON.stringify(cart)); }, [cart]);
  useEffect(() => { localStorage.setItem("smart-cart-bag", String(bagSelected)); }, [bagSelected]);
  const items = useMemo(() => products.filter(p => cart[p.name]).map(p => ({ ...p, qty: cart[p.name] })), [products, cart]);
  const count = items.reduce((n, p) => n + p.qty, 0); const subtotal = items.reduce((n, p) => n + p.price * p.qty, 0);
  useEffect(() => { if (!items.length) { setRecommendations([]); return; } fetch(`${API}/recommendations`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ product_names: items.map(p => p.name) }) }).then(r => r.ok ? r.json() : Promise.reject()).then(setRecommendations).catch(() => setRecommendations([])); }, [items]);
  const change = (name, delta) => setCart(c => ({ ...c, [name]: Math.max(0, (c[name] || 0) + delta) }));
  const registerDetection = productName => { if (lastRegisteredRef.current === productName) return false; lastRegisteredRef.current = productName; setLastRecognition(productName); change(productName, 1); setRecognitionToast(productName); window.clearTimeout(toastTimerRef.current); toastTimerRef.current = window.setTimeout(() => setRecognitionToast(null), 3200); return true; };
  const markProductLeftFrame = name => { if (lastRegisteredRef.current === name) setPendingExit(name); };
  const resolveProductExit = removeOne => { if (!pendingExit) return; lastRegisteredRef.current = ""; if (removeOne) change(pendingExit, -1); setPendingExit(null); };
  const scan = async video => { if (!video || scanInFlightRef.current || video.readyState < 2) return; scanInFlightRef.current = true; setScanState("scanning"); const canvas = document.createElement("canvas"); canvas.width = video.videoWidth || 640; canvas.height = video.videoHeight || 480; canvas.getContext("2d").drawImage(video, 0, 0, canvas.width, canvas.height); try { const response = await fetch(`${API}/detect`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ image: canvas.toDataURL("image/jpeg", .8) }) }); const result = await response.json(); if (result.error) { console.warn("Roboflow 추론 오류:", result.error); candidateRef.current = { name: null, count: 0 }; setDebugInfo({ status: "인식 서버 오류", raw: "-", mapped: "-", count: 0, error: result.error }); return; } const topPrediction = [...(result.predictions || [])].sort((a, b) => (b.confidence || 0) - (a.confidence || 0))[0]; const confidence = Number(topPrediction?.confidence || 0); const confidencePercent = Math.round(confidence <= 1 ? confidence * 100 : confidence); const raw = topPrediction ? `${topPrediction.class} (${confidencePercent}%)` : "감지 결과 없음"; if (topPrediction && confidencePercent < MIN_CONFIDENCE_PERCENT) { candidateRef.current = { name: null, count: 0 }; setDebugInfo({ status: `신뢰도 미달 (${MIN_CONFIDENCE_PERCENT}% 이상 필요)`, raw, mapped: "-", count: 0, error: "" }); return; } const productName = topPrediction && resolveProductName(topPrediction.class, products); if (!productName) { candidateRef.current = { name: null, count: 0 }; setDebugInfo({ status: topPrediction ? "DB 상품명 연결 실패" : "상품을 찾지 못함", raw, mapped: "-", count: 0, error: "" }); return; } candidateRef.current = candidateRef.current.name === productName ? { name: productName, count: candidateRef.current.count + 1 } : { name: productName, count: 1 }; const confirmed = candidateRef.current.count >= CONFIRMATION_FRAMES; setDebugInfo({ status: confirmed ? "장바구니 등록 완료" : "등록 전 재확인 중", raw, mapped: productName, count: candidateRef.current.count, error: "" }); if (confirmed) registerDetection(productName); } catch (error) { console.warn("인식 서버 연결 오류:", error); candidateRef.current = { name: null, count: 0 }; setDebugInfo({ status: "서버 연결 실패", raw: "-", mapped: "-", count: 0, error: error.message || "Failed to fetch" }); } finally { setScanState("ready"); scanInFlightRef.current = false; } };
  useEffect(() => { scanRef.current = scan; }, [scan]);
  useEffect(() => { if (view !== "main" || !stream) return undefined; const timer = setInterval(() => scanRef.current?.(mainVideoRef.current), 1800); return () => clearInterval(timer); }, [view, stream]);
  if (view === "camera") return <Camera stream={stream} cameraError={cameraError} lastRecognition={lastRecognition} recognitionToast={recognitionToast} debugInfo={debugInfo} showDebug={showDebug} pendingExit={pendingExit} onBack={() => { setScanState("ready"); setView("main"); }} onScan={scan} onProductLeftFrame={markProductLeftFrame} onResolveExit={resolveProductExit} />;
  if (view === "recipe") return <RecipeDetail recipe={selectedRecipe} onBack={() => setView("main")} />;
  if (view === "detail") return <Detail items={items} subtotal={subtotal} bagSelected={bagSelected} onToggleBag={() => setBagSelected(value => !value)} recommendations={recommendations} change={change} onRemove={name => setCart(c => ({ ...c, [name]: 0 }))} onBack={() => setView("main")} onPay={() => { setPaymentComplete(false); setView("barcode"); }} />;
  if (view === "barcode") return <BarcodeCheckout count={count} total={subtotal + (bagSelected ? 500 : 0)} bagSelected={bagSelected} completed={paymentComplete} onBack={() => setView("main")} onComplete={() => { setCart({}); setBagSelected(false); setLastRecognition(null); setRecognitionToast(null); lastRegisteredRef.current = ""; candidateRef.current = { name: null, count: 0 }; setPaymentComplete(true); }} onFinish={() => setView("main")} />;
  return <main><div className="app-shell"><nav className="rail"><button className="rail-cart" onClick={() => setView("detail")}><ShoppingCart size={21}/><i>{count}</i></button><button className="rail-scan" onClick={() => { setPaymentComplete(false); setView("barcode"); }} aria-label="바코드 스캔 결제"><ScanLine size={20}/></button><span className="online" /></nav><div className="app-content"><header><div><small>LIVE RECOGNITION · CART 08-41</small><h1>스마트 카트</h1></div><button className="status status-toggle" onClick={() => setShowDebug(value => !value)} aria-pressed={showDebug}>● 카메라 {cameraError ? "연결 필요" : "정상 작동"}{showDebug ? " · 디버그 ON" : ""}</button></header><div className="hero-grid"><button className="camera" onClick={() => setView("camera")}><video ref={element => { mainVideoRef.current = element; attachStream(element, stream); }} className="camera-video" autoPlay muted playsInline/>{cameraError && <span className="camera-error">{cameraError}</span>}{showDebug && <DebugPanel info={debugInfo} compact/>}{recognitionToast && <span className="recognition-toast compact">{recognitionToast} · 장바구니에 추가됨</span>}</button><StatusCard count={count} items={items} lastRecognition={lastRecognition}/></div>{recommendations.length > 0 && <MenuBoard recipes={recommendations} onOpenRecipe={recipe => { setSelectedRecipe(recipe); setView("recipe"); }}/>}</div></div></main>;
}

function StatusCard({ count, items, lastRecognition }) { return <aside className="status-card"><small>SHOPPING STATUS</small><p>카트 내 상품</p><strong>{count}<em> items</em></strong><div className="status-items">{items.length === 0 ? <span>아직 담긴 상품이 없습니다.</span> : items.map(p => <div key={p.name}><span>{p.name} <b>× {p.qty}</b></span><strong>{money.format(p.price * p.qty)}</strong></div>)}</div><div className="recent">최근 인식: {lastRecognition || "없음"}</div></aside>; }
function MenuBoard({ recipes, onOpenRecipe }) { return <section className="menu-board"><div className="panel-title"><span>오늘의 메뉴</span><span>RECIPES FROM DATABASE</span></div><div className="menu-grid">{recipes.slice(0, 5).map((recipe, i) => <article key={recipe.id || i} className="menu-card" role="button" tabIndex={0} onClick={() => onOpenRecipe(recipe)} onKeyDown={event => { if (event.key === "Enter" || event.key === " ") onOpenRecipe(recipe); }}><span className="menu-number">0{i + 1}</span><div><h2>{recipe.name}</h2><p>{recipe.description || "마트 상품으로 만들 수 있는 추천 요리"}</p><small>{recipe.cook_time_minutes || 20}분 조리</small></div><ArrowRight className="recipe-arrow" size={18}/></article>)}</div></section>; }

function DebugPanel({ info, compact = false }) { return <span className={`debug-panel${compact ? " compact" : ""}`}><b>DEBUG · MODEL RESPONSE</b><span>상태: {info.status}</span><span>모델 결과: {info.raw}</span><span>DB 연결: {info.mapped}</span>{info.count > 0 && <span>연속 확인: {Math.min(info.count, CONFIRMATION_FRAMES)} / {CONFIRMATION_FRAMES}</span>}{info.error && <span className="debug-error">오류: {info.error}</span>}</span>; }

function Camera({ stream, cameraError, lastRecognition, recognitionToast, debugInfo, showDebug, pendingExit, onBack, onScan, onProductLeftFrame, onResolveExit }) { const videoRef = useRef(null); const scanRef = useRef(onScan); useEffect(() => { scanRef.current = onScan; }, [onScan]); useEffect(() => { if (!stream) return undefined; const timer = setInterval(() => scanRef.current(videoRef.current), 1800); return () => clearInterval(timer); }, [stream]); return <main className="dark-page"><div className="camera-full"><video ref={element => { videoRef.current = element; attachStream(element, stream); }} className="camera-video" autoPlay muted playsInline/><div className="camera-shade"/>{cameraError && <div className="camera-error">{cameraError}</div>}<button className="camera-close" onClick={onBack} aria-label="카메라 닫기" title="카메라 닫기">×</button>{showDebug && <DebugPanel info={debugInfo}/>}<div className="focus-box"><i/></div>{recognitionToast && <div className="recognition-toast">{recognitionToast} · 장바구니에 추가됨</div>}{lastRecognition && <button className="frame-reset" onClick={() => onProductLeftFrame(lastRecognition)}>상품이 카메라에서 사라짐</button>}{pendingExit && <div className="added-modal exit-modal"><h2>상품이 사라졌어요</h2><p><b>{pendingExit}</b> 상품을 장바구니에서 1개 뺄까요?</p><p className="dedupe-hint">아니오를 선택해도 다음에 다시 나타나면 새 상품으로 인식합니다.</p><div className="confirm-actions"><button onClick={() => onResolveExit(false)}>아니오</button><button className="confirm-delete" onClick={() => onResolveExit(true)}>예, 1개 빼기</button></div></div>}</div></main>; }

function RecipeDetail({ recipe: summary, onBack }) {
  const [detail, setDetail] = useState(null);
  const [error, setError] = useState("");
  useEffect(() => {
    if (!summary?.id) return;
    setDetail(null); setError("");
    fetch(`${API}/recipes/${summary.id}`).then(response => response.ok ? response.json() : Promise.reject()).then(setDetail).catch(() => setError("레시피 정보를 불러오지 못했습니다. 백엔드 서버를 다시 실행해 주세요."));
  }, [summary?.id]);
  const recipe = detail?.recipe || summary || {};
  const ingredients = detail?.ingredients || [];
  const instructions = recipe.instructions || recipe.method || recipe.recipe || "조리 방법 정보를 준비하고 있습니다.";
  return <main><div className="recipe-shell"><button className="back" onClick={onBack}>← 오늘의 메뉴로 돌아가기</button><header className="recipe-heading"><small>TODAY'S RECIPE</small><h1>{recipe.name}</h1><p>{recipe.description || "장바구니 상품으로 만들 수 있는 추천 요리입니다."}</p><span>{recipe.cook_time_minutes || 20}분 조리</span></header>{error ? <p className="recipe-error">{error}</p> : <div className="recipe-grid"><section className="recipe-method"><small>HOW TO COOK</small><h2>간단 레시피</h2><p>{instructions}</p>{recipe.source_url && <a href={recipe.source_url} target="_blank" rel="noreferrer">원본 레시피 보기 <ArrowRight size={15}/></a>}</section><aside className="recipe-ingredients"><small>INGREDIENTS</small><h2>들어가는 재료</h2>{detail === null ? <p>레시피 정보를 불러오는 중…</p> : <ul>{ingredients.map((ingredient, index) => <li key={ingredient.id || index}><span>{ingredient.product_name || ingredient.ingredient_name || ingredient.name || "재료"}</span><b>{ingredient.amount || ingredient.quantity || ingredient.unit || "필요량"}</b></li>)}</ul>}</aside></div>}</div></main>;
}

function Detail({ items, subtotal, bagSelected, onToggleBag, recommendations, change, onRemove, onBack, onPay }) { const [pending, setPending] = useState(null); const total = subtotal + (bagSelected ? 500 : 0); return <main><div className="detail-shell"><button className="back" onClick={onBack}>← 쇼핑 계속하기</button><div className="detail-grid"><section><small>YOUR SELECTION</small><h1>장바구니 상세</h1><div className="detail-list">{items.length === 0 ? <p className="empty-detail">장바구니가 비어 있습니다.</p> : items.map(p => <div className="detail-row" key={p.name}><span className="thumb">{p.name.slice(0, 1)}</span><div className="detail-info"><b>{p.name}</b><small>{p.unit} · 국내산</small><small className="location"><MapPin size={13}/> 식품 {p.zone} · {p.storage_type}</small></div><div className="qty"><button onClick={() => change(p.name, -1)}><Minus size={14}/></button><span>{p.qty}</span><button onClick={() => change(p.name, 1)}><Plus size={14}/></button></div><div className="detail-price"><b>{money.format(p.price * p.qty)}</b><button className="remove-button" onClick={() => setPending(p.name)}><Trash2 size={14}/> 삭제</button></div></div>)}</div></section><aside className="order-card"><small>ORDER TOTAL</small><p>상품 금액 <span>{money.format(subtotal)}</span></p><label className="bag-option"><input type="checkbox" checked={bagSelected} onChange={onToggleBag}/><span>포장봉투 구매 <small>500원</small></span></label><div className="order-total"><span>예상 합계</span><b>{money.format(total)}</b></div>{recommendations.length > 0 && <p className="recommend-note">추천 메뉴: {recommendations.map(r => r.name).join(" · ")}</p>}<button className="primary" onClick={onPay} disabled={!items.length}>결제 바코드 열기 <ArrowRight size={17}/></button></aside></div>{pending && <div className="confirm-backdrop"><div className="confirm-modal"><h2>상품을 제거할까요?</h2><p><b>{pending}</b> 상품을 장바구니에서 제거하시겠습니까?</p><div className="confirm-actions"><button onClick={() => setPending(null)}>아니오</button><button className="confirm-delete" onClick={() => { onRemove(pending); setPending(null); }}>예, 제거하기</button></div></div></div>}</div></main>; }
function BarcodeCheckout({ count, total, bagSelected, completed, onBack, onComplete, onFinish }) { return <main className="dark-page"><div className="barcode-shell">{completed ? <div className="barcode-content payment-done"><span className="payment-check">✓</span><small>PAYMENT COMPLETE</small><h1>결제가 완료<br/>되었어요.</h1><p>이용해 주셔서 감사합니다.</p><button className="primary" onClick={onFinish}>확인</button></div> : <><button className="back light" onClick={onBack}>← 메인으로 돌아가기</button><div className="barcode-content"><small>SMART CHECKOUT</small><h1>결제 바코드를<br/>스캔해 주세요.</h1><div className="barcode-frame"><div className="barcode-pattern">{Array.from({ length: 34 }, (_, index) => <i key={index} className={index % 5 === 0 ? "wide" : ""}/>)}</div><span className="barcode-line"/></div><p>카트 상품 {count}개{bagSelected ? " · 포장봉투 1개" : ""} · 결제 예정 금액</p><b>{money.format(total)}</b><button className="primary payment-button" onClick={onComplete} disabled={!count}>✓ 결제 완료</button>{!count && <small className="barcode-empty">장바구니에 상품을 담으면 결제를 진행할 수 있습니다.</small>}</div></>}</div></main>; }

createRoot(document.getElementById("root")).render(<App/>);
